# ArgoCD Helm 차트 설정값 (필수 설정만 포함)

# 관리자 계정 및 서버 설정
server:
  # 개발 환경용 인증 우회 설정
  extraArgs:
    - --insecure
  
  # 인그레스 설정
  ingress:
    enabled: ${ingress_enabled}
    hosts:
      - ${ingress_host}
    ingressClassName: ${ingress_class}
    annotations: ${ingress_annotations}

# 보안 설정
configs:
  secret:
    # 관리자 비밀번호 해시 사용
    argocdServerAdminPassword: "${admin_password_hash}"
  
  # Git 저장소 설정
  repositories:
    # Helm 차트 저장소 설정
    helm-charts:
      url: "${helm_charts_repo_url}"
      type: git
      # insecure: "true"

  # ECR 접근을 위한 크레덴셜 템플릿
  credentialTemplates:
    aws-ecr:
      url: https://{{.awsAccountID}}.dkr.ecr.{{.awsRegion}}.amazonaws.com
      password: "{{.awsCredentials}}"
      username: AWS

# RBAC 설정
rbac:
  policy.default: role:admin
